### ISSUE TITLE
Gps track shift after zoom in/out

### ISSUE THREAD

**Issue by Gar5** [SM-Sergey/RMaps-ng#3]
it's glad to use rmaps again, this offline map is the best I ever tried, user friendly, no complicated and useless functions, simple, clean and power safe, but I found that the track is shifted after zoom in/out, sometime is located at the right place, that make me can't use, just record track only.

and there are black zone at top and bottom, could you please adjust that can fully use the screen to clearly check the map, my phone is pixel 5.

thx!
![image](https://user-images.githubusercontent.com/78244720/106345573-38d1a780-62ec-11eb-93df-b1cbc5d7f9c4.png)

**Comment by SM-Sergey** [comment]
Fixed in pre-13.
